# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: observability
stringData:
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:cLoD9/9EzOV+FAUcuZzV3M6LEVsiYy8Cel1eZTyv,iv:HKu7pe3OohPkpvSYTsw2MGixZCeNyy/otV+58GOX1XQ=,tag:1LJFLGjA8O40uAs4sE0ZQQ==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:ys+dAV3uqg1k9tANB6oPd7xmZiyFTEDr9I/Kh3GR,iv:IXFBQXj5Pn1onRKOqbcVEfFPNjkWo/pexTvXN6QPOXQ=,tag:jQqKIiBZC13hOQ/TLunf7w==,type:str]
  ALERTMANAGER_HEARTBEAT_URL: ENC[AES256_GCM,data:i3PZPlSCtGPtUB5zHbYhd3ZCf6B6NX6z+etE4ckJ2AjgAbQ6zmVNiEGFRviJ0iww0ghYQig1oXY=,iv:HNqcnV3AGDD9FfdhQligXParGG77oMWfdINv/o1/ZGs=,tag:AatoF4f/IqlVnuLMcp3Nnw==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSmJqVFRrSGJiTUNCa1dK
        YkI2ZjZBRTBIc3h6RnliV3dySWdQQ2NvRUZ3ClprQ2xTMVk3c0pTaFRKeURwMFc0
        aDREQXpMY09IY1VzcFFiWjEvMG05eVkKLS0tIDFFVDFNUUljeDdxSDM3U1pNeTh3
        S2c4UFJIVG0xZlVqRVUva2VpQlBPR00KEJ6SwG70xkChtB+d0yPnXxilv7wXtg/Y
        Sw9TCjBpIJUgAe2DBJaQygc+uda4FAweW510Awm0UGDsCg4//2HFoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T22:10:29Z"
  mac: ENC[AES256_GCM,data:t5muNMbWHHEHLPi6jQV+vwPnaXiJ1JS5IuWSQGjskhBSz5dOK09LRvLue/oJsv0J1HG/dHeT58liMbozX8GJPnK6aYQsd/H4AnfOMS78ZQ37aemNFcRuA+yIV3gdpgbx8SQmhkBrC/+mdadRclYb75z9XoXMwptDdlrU9BXbKJE=,iv:Zgj25PvEFQ1b68VLJx3fOsHWmnYflS9+ArJLnilcUuA=,tag:ZPrkM9YIvDbTEX2EnmSEeA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
