# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: observability
stringData:
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:cLoD9/9EzOV+FAUcuZzV3M6LEVsiYy8Cel1eZTyv,iv:HKu7pe3OohPkpvSYTsw2MGixZCeNyy/otV+58GOX1XQ=,tag:1LJFLGjA8O40uAs4sE0ZQQ==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:ys+dAV3uqg1k9tANB6oPd7xmZiyFTEDr9I/Kh3GR,iv:IXFBQXj5Pn1onRKOqbcVEfFPNjkWo/pexTvXN6QPOXQ=,tag:jQqKIiBZC13hOQ/TLunf7w==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSmJqVFRrSGJiTUNCa1dK
        YkI2ZjZBRTBIc3h6RnliV3dySWdQQ2NvRUZ3ClprQ2xTMVk3c0pTaFRKeURwMFc0
        aDREQXpMY09IY1VzcFFiWjEvMG05eVkKLS0tIDFFVDFNUUljeDdxSDM3U1pNeTh3
        S2c4UFJIVG0xZlVqRVUva2VpQlBPR00KEJ6SwG70xkChtB+d0yPnXxilv7wXtg/Y
        Sw9TCjBpIJUgAe2DBJaQygc+uda4FAweW510Awm0UGDsCg4//2HFoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T03:24:28Z"
  mac: ENC[AES256_GCM,data:yw4hUkhdUkf3PUwSxuzTFVfB/mHb+wQdqHNaK0sy/mq8L8xzwy5XifP3ZoMc/SWvO0lPVDehTMCv7AHydEKgm2xWnTpcrskTrMiUFmmOzgoQaSIJrOdB8L9nyt2Ac7/qgz6q93A5CKFaiQVtQp0C55gGmIbFwKJBu6vILaLq8ig=,iv:pvXRrOYqe8k6Wr1U1Nmz5kzlqQ23M/ggMXS2klTBsuo=,tag:7E3H4T9UNy1lvcovR0YYTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
