---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-status-app
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-status-app
    template:
      data:
        githubAppID: "{{ .FLUX_GITHUB_APP_ID }}"
        githubAppInstallationID: "{{ .FLUX_GITHUB_INSTALLATION_ID }}"
        githubAppPrivateKey: "{{ .FLUX_GITHUB_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: github
