# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant
  namespace: home
stringData:
  HASS_LATITUDE: ENC[AES256_GCM,data:cjDovEVdpWbZUdUqFp7fkxVg,iv:1iQTDlkxT/hZG8/sQktu5bzZg+KyCg3rm9d9e2/UV3Y=,tag:OBn7wHWIZ8OcRKoJ/bfFPA==,type:str]
  HASS_LONGITUDE: ENC[AES256_GCM,data:9qgVjvWqCpd4bZE748qpNQDM,iv:DpdenUERekLdW9lNTeHGlVxleszuX3a4vmIkHFrXams=,tag:8HZgxMDmgy2Ne07fYlVJSw==,type:str]
  HASS_EMAIL: ENC[AES256_GCM,data:wcx8XoDXSroxpDL7fyyfI17E,iv:scgx9y/F97U4f9mCyzslhua74zOtUhzY0r8euYbaXDU=,tag:bLBpVvtlfJZAOA3NdO4WqQ==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNV1RReTlJbEJBNmZKWEVr
        aDUxVUY2enB4REJYS1hlcGUxZUdVenUzdkJFCmI4MEhURGJETitUKzNxazZ1Z1U0
        REt3UmRldllSa1lWbXJWemNZVGFMU2cKLS0tIE1GYU5odTZJdjVWZm5UVkgweFJB
        a2FyWU5zUUdaRlRKOHcxTkNZNzNmSjgKs/1UvM7xGh/oI3HxEmQg0UeE5SNkSRvj
        D8tf2wV+5afInObYaanegw7be8pwUeFI1cjXFLINUyij5Z78EaA2ow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T18:13:31Z"
  mac: ENC[AES256_GCM,data:m4727ypQDGKuC7NByQ4b1SAuLqW7wK+ojFrRQ7JBbU7gizc3kqA5u6IfXbdO5FIw7sEpHJcKcWBQsjR0QIaKTRmrX75wvxA2Sxf15wl+DemKLb9lDP+tSuzJooizfNBiYJqNOYord0Q5Inhc5AkwpzjDY/Q/X/NmoXpgGcpg3Uo=,iv:/sxHoHhFwRCeaNLThW1TyKI5skHo7BpJH6JTbGqq9/E=,tag:AJ1psdXw1VSpcaBHjTvolg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
