---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./aeotec-zwave-device.yaml
  - ./google-coral-device.yaml
  - ./sonoff-zigbee-device.yaml
