apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:7a3SYK626c/Hh/vaEVO7P1tER2sjXg9e9URREm1jBBqYVDT9tb/QVQ==,iv:V0acBSBzo91iNSXfkL+i1M2qQJ3RoXCAAf/M6bDaexc=,tag:qqaEIs5o5E+F/S7Wk3AC0A==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYmdZT0N3YUtuR0g0YmxV
        SHFCSnBqR1pPMGF4aWcwT0dKTVFhR2JVZm04CkhUQ3ZFOWdVbTNGL1MxclJFV0lz
        M0ZUdHR6RnBxcWJDdHFPYUtnK0hqU0UKLS0tIEFCdERyWFIyMURsZVlvTlBBN3Np
        YnNzRWFlblV2SUpMR0xiZnIwb3hWREkK4whGegkeDMqwv8zJeR6+znrgZYWjQjHA
        DHiYZdgsqPJ/OLCbYiOEOn7JLrASfTG1UbrMwtCodi5NWKIOqfJnAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T01:13:07Z"
  mac: ENC[AES256_GCM,data:BIfNWQU2oSnpH6tyfJFzrwI/hrtAkP58V+UL17meubq8Vc+l5Iv9Z0Z1V7jpb0uPkAZJUu6yZfIuvRgZpqjLN2Dt72EtrHaWizofCe1ZSTbCPDkNIzuAp2RvvXI16AoXor7PjttK4CqZbMhZeQMkio/mwdeBX+SB7qcio3KOFcM=,iv:sAZgjHdHJ69qaqldBsW8hTaY7LM967vs2I5USqtjXh0=,tag:cD32M0MDWUl4C3aIcd6CYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
