apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:VIzuaQ6LX/ZfrXnNRe2twNDFrPMKcsZd/Dsn4efrES1rICqlc02GyQ==,iv:tahfL/xpBW2IjTKE8tNADU82wDKRuPs7Kl9sYQvk+2U=,tag:/ZdSPIKXQ9wnn4eNLZL4rg==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaWdZeU8zNWFLTGVia1pk
        WnJZMEx3Y0RFME44MEhxWE5qZ2tBbkVFQXlBCnZQVnRlQkhDMEp1ZWg3ZTBqWTAz
        WUw4ZzNXZnV4aEFxblFxRXZkRVJUOHcKLS0tIDBGVEdkYndxVkwvMUxrU0RsWENo
        TEZOOGhYZFpTbFpnQ0pkMkp6OGR5VEUKy98nDN7GeGjWSHOkzl0V8Vtf/0RkRxCb
        NA+rhHym7tWzyBv3NuSxlbEaD7BmRxftRxsXmO1m7yL5H7kTU9Ct6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T21:27:22Z"
  mac: ENC[AES256_GCM,data:5Gz9CqL9nmWCSMlJpT6wiXptevpNAFGtxHeGv535vQsvBVr0i0I3kt32FdDB76dvKFLTKuPqWHfscp8TQ/B0ELYznJ7vBtX1qxmVYrAs2wl30FflcthIt80koJh0l/kyUD6WSICE+XbiJdI0GiT56yI5OqfDUmWjNGdtvzS4wg4=,iv:ZCypDII2p0Yd9e2ZWFqtVwHNvNRraxuqduvo/IRpPCA=,tag:cWDmL+X2fb/xxRi+I7KGgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
