apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:J1oPw0AetLpCcCxumjZQaGxuHCOB7F/MalNL6SmwFcuB38CzbnJ7+A==,iv:348LmNrvHTxTsqDc0BNAKzFE6SPg/75f7Qf9nlNLNdo=,tag:pAL6Z0VlGEuUHPLo688y8A==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVW5pOWFPMEc0UDF1US9I
        b1FFa2M3YUV5b3NaZEhQSDhwN2hKeTdESkRjCnp2WHFpMFZjL2xDSlh5LzVwN1Fo
        U2MvbElTN3NDRmJ6bFExZEU2MmxZQmMKLS0tIFcvdml5M1lMbmp2Mzhvc09SeVFa
        bklydHRGNFZHdHdzdFROWTA1aGQ2VGMKWiQt3+XMZPMNoeMpfuDwUQfrk4OpC66N
        IYn7ASpOZs2uUsPreZ1C0obby5sB16mWDjGT+mNBlC6TBuev0iFCOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T02:45:25Z"
  mac: ENC[AES256_GCM,data:+Z+nI4Xz47+ZRJz0B9jAZtKMaeqx5udfqw7If+q4cTVv+03EiJdVHB8YL9xMIqiZg8LcGhg2/R4Yz+Oo2U8X2lzosiesE167moprH0OGa33iJDQ92g5ZWR066rLhLcewZOh88iXorHYcJfxQpSPHVhxRSLi/UFwoWGON/55MErA=,iv:rchmsmQrzLcITojjCjTWpnJ8vXUtOZ4q055w8gea6gA=,tag:CoiCGqQjlbRA66Pra9bfLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
