# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:GSPinq/ZZcSJgkI=,iv:dJ+yJP/9pEf+DPYp7TSMwRWwMAvCCWO+hPnZIxL00p8=,tag:CR2XldKCrwUcTsj9rj+k1Q==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:UJKxlIHAZrqBi+C/4YMXzfCJmrh4nMHIvwOaSTvuJ8KEJJMNGjC2mp2BWw7gyQyi,iv:jTV6T6z7FJ0sw25e32oLoH+7Y86HzDNpCJ8FqtRG62E=,tag:BNAOF8fGCndBTfZfaRAAFA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:4+HFbLrfkta0GwX0xIVii2/knLv5uT9+,iv:tkGBH9zcc7X2Uu3qL6+IzrumpjXEiJb+6w9zBn8qDuA=,tag:kSVCBIxAM/oEcjYjZQHMlQ==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZzRvcnlleGY2ZzlrMldE
        VUdjYjkzRTdja3dXR1doV0VUaGhoZW1zV2lzCnpZNkdMcDNWSmQ0eUNjZWFqMnpE
        MWIxcGc0b0VMemZFWW8veDk0bTNab3MKLS0tIEh0L3p6RWM1ZlhqOUxzMElKU2E1
        eWU5SGlDSmE5Qnl1NDRTSzh0RXJIbkkK91XXTENOuGQKMs9A//Euo6T/bqmp0Q2F
        Iz+mpMCwB2yonCwRdubGfDBoeTMs6TdBwEDvw3ZJ71cSU/VR8taAWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-18T23:47:58Z"
  mac: ENC[AES256_GCM,data:Mgi2ccifK7v/Ovb4/4PRGNruqxKu9atU2HT+snm7Az+pUPOKMQck61qaXid0UDBw5nn56OgdVp8AS4G8KBAkcLrH4FIB6/DhR1flc2HeWKC97k72hf2GG+k3Rl6Qra1rotmcNkvtGYy29IbJYjAcDj5LY3gULr+N8kiyXXNOPnU=,iv:mgC5LJKO2SxR14G554r8LYpySYUH+YMou4sX/yoMvA8=,tag:WBh60kRUDxA01BlDKkJ6OA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
