apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:EqLXKF9aHBK6v4a93Rh8rz4VCUY=,iv:zfFpvIsxtslqtiQjdzKq9gbZbHb28QvgeVR7+IA2aew=,tag:QT2GX3/Yo9D+wcsWsjwxgA==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNVN5MVBTMkEzMDJvYldS
        TEZHb09lalFHYUdIOXJoRmdyM1l4U2I1RWxFCmdHbGtRdUpTc0JuYU1JTlMvUC8z
        dG80QnNrWFUyTEhsVERIZENGTDJhdTAKLS0tIEhlcnhrMy9wb1lDYlQxRWdHK3J5
        a01rTmhuR2FZcGxrVXF2azJLT2gzT2sKAo7a/XIC6MZbtcHPpioKkveGKZ6FFHpN
        kA2icJSkB27QQobjAsL8rJ0tPA8nqHkpVphKTYJ6RPCds16fZmaZ6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T04:19:37Z"
  mac: ENC[AES256_GCM,data:1QBEv2sGxbxWUTZ0Ers/lX2mCGg6oKRezyGXH8OZbxb1yuUNb5favJg+lOB0hx84/OKJRz/HlEAj6Wf3QOBPa4Q0YK7v5hyon0P4eS1ciJiATW6Zw1rU7dwBeSYxVL1P850XIjCNfcKNbNYnngHMD3KduV7ugZANs0O+OIenAQM=,iv:0vq8vG59DmfH2lWLBG+ZBBo6z79zpxGd/LpNGJ4aWJs=,tag:s3jK0AU662qJXnDIVQymdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
