apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ov203JZxISEo4RRcSQJmiA==,iv:FpPC6o7CYnptnxvrsONS0FVPb77HmEkQEjXWLHukg7o=,tag:ExSXMfN9MDz+ijJnUtpryw==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYUhoUzBMTXVIRTdCSDdS
        eFE5SHA4dEVkYWFSM3AvWGp1V0FiMCt4STNzCmNuanVWZng1NVBlZm5lTXg0bGVC
        cGU2anZ4TzNzOEV2dWlDNU9IV3E1YWcKLS0tIDVWMzc2eVFVN1l2TExsbWkwTVY2
        Qi9PSGFvQWprMzRadWdGd3A1UXFVYVUK7FiMmtuhKAYpc1L6OAM/t+ORL6Q6aiL0
        RZE5cJsqVbZyfxqWlzT39Yry3yZFn/iPydy5H094J7+iyKvnv2MhzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T02:45:25Z"
  mac: ENC[AES256_GCM,data:cxydEfrQZoHx3AQio9tiMr50uMUdk88LNb3mL6OlmvUGDKSYcy5aTs953EUDH5k+HUZNzSuhlEjNA0nBBOY2ib2kfTshQZ6jvAV6dlQpi8N8lMZTI8inybDQjT8pHQwZ992XlZ+YaCNfZtNi1kGNCVTMtuVlEfZ09RoHTXERDXc=,iv:K37XZNy43ueyaqgi5LWUVC0aSGjlFAERU5mlkJdAx1A=,tag:ArhNlqpKloOafL1WR5WqZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
