apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:HglmQxhW3Ite6dOd31nnVG96zAk=,iv:AZYGqnx7LJPY2Roe78mivZF5vBQFBL4/m0XaFSZjuJ0=,tag:hgRmsNexB54VMVz1Krxvnw==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNVN5MVBTMkEzMDJvYldS
        TEZHb09lalFHYUdIOXJoRmdyM1l4U2I1RWxFCmdHbGtRdUpTc0JuYU1JTlMvUC8z
        dG80QnNrWFUyTEhsVERIZENGTDJhdTAKLS0tIEhlcnhrMy9wb1lDYlQxRWdHK3J5
        a01rTmhuR2FZcGxrVXF2azJLT2gzT2sKAo7a/XIC6MZbtcHPpioKkveGKZ6FFHpN
        kA2icJSkB27QQobjAsL8rJ0tPA8nqHkpVphKTYJ6RPCds16fZmaZ6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T21:27:21Z"
  mac: ENC[AES256_GCM,data:9mtU5KLwZ+IOnT4Mc1IIVAY3zKXSm+GkNSoSjPhUCCJdH1iL2tuUaLkjtd453BxPWfu5Z1N8NYAiGLnt7X9d9wrFlA6xY/gIufwv613WJ4d8GGakj+k11d+m0zbvxcS1iPVbphHFnfIaPEsfMhRjShWl9Cpi+1GTPRDUhf4/6hM=,iv:sijefqFIF4AwgHSLJsPJRLr0ENvWdyvO0FB4Hkf4Rlw=,tag:/FKj+Otkxbwo33JYKPhGTA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
