apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:aXsb7jdqbD1RSQ58/yRmyw==,iv:QLbfU4j8Kgh//I6xcEefec+iNvSGXrIiJfH6gDTbUek=,tag:i4H9AodKo/U1YTzO9X8gZg==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMjJTRVQ3V1l4cUh6NXZY
        ajd0b0pKcVdQZTdhdUk3YlNQOUtmOFpUV2hZCjB0c2QrOFZIWmtzWk5SN0dFWFNF
        L1RmbEpISmwxWnVrbHNTd250ZnR0YkUKLS0tIDgxSEhyQVVYeHBvRndNcWpCeWsr
        WG1KNWI0RGVSYmlkeExKZHFaVmUrbTAKNYDQwJSkymnzjVbsBx5FZGhp7DJSzpeS
        Uf2zVD5AS/8klrrOlu2NC5KVuLrMvl3zpJpZ9pisFuD04+HA/2kKag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T01:13:07Z"
  mac: ENC[AES256_GCM,data:SBssnic/eV21BvRexYD/n7wqzFVzSDsTW3D18ZDLpcLvzR7pQOtxf2ljPf/6x6ekNA1X35aSjILSpWSQrlPbw3Fh6PKOhJSj+Fudr2dno6KhPX+n1UCoDjBljs4gT2lLgWdoF00qs4+d+XsQrosB+jBPaTUxe+kBCBx74Sak8Ho=,iv:rF/i80t3it3A3ORzF4VjrMddQAF8e0dK+LmjjyHz79s=,tag:fa8yxGeF9UT48nl+Aca/7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
