apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:tbA6t7KOhYWR1pY+BR1giJ1/iwx3+WmEHn9k+oqMwsc=,iv:4AxcACCfEYk2i8cDDWWFvTbh6N5OAY1lrrhG42PHkY4=,tag:PvyzCkWGEXf4jkLYowVs5w==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSa1NJa3ViUDZUaFJuOVdn
        d2tLbjZ1dUlaMWdTWWl0M25KbVB1dHd1a1JFCmdmaW5wait1amhiVDhGakpkVEFR
        Nm9IUkwxRXN4d0wwenA2bCsvVHdOTW8KLS0tIFRyZ0FqTWY3M0hhbExLQzAxN3ky
        NzFEeG9VVmVTNERLZ280NW1abGRUVjgK3WXeH7tUB02PT40tlBJ8L1SfHih+jzF3
        19OEJPteT0OHyZqayf5MhiWiQGdlX9Zu1PFB4Skp8XGcdcbx4hJGXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T21:27:21Z"
  mac: ENC[AES256_GCM,data:7SXC+zb2Oq8DV11RF2W1E55xqQmZYTblfBB3f7A97vVwNMjMHIedERHmicb7cKpvi5ABZ1D3Kly6MJaMGhqTS6oajmjiPJWBIqkhBrvJlNJ2OJJVUHAAiKONSZEEOV6JRk9BODsgK5zlkVAgPAXRDjCWO2v4v9JDJSE/XhK9+4I=,iv:lcyvZ/WWU3iz6pK9JRW0LwEv4t6TNW/+n4140prX2vw=,tag:FbEIvzqoBWTzQ0hx6GL01Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
