apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:S1VP/bW2U9NhaMOjp9KVeGccH5glYhmM9Sc+GuXyEuM=,iv:QYpPiqeVbjW9fR4dP0fuBUmr30cn5q8nKGizWmrkcts=,tag:r7rH+AErvkrPYsk6zYKd9A==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcVFoWndyR21Zak9yc1JS
        OVpya3RPekQ3RExiMWxyOW4vNmhzYmxrODNVCmhLSGJpY0p0V3FocTZONk9wejlP
        UHhnMGxFaEwvdkl4dU9wZjkvK2Z0cEEKLS0tIFN4THFsY1NCZW1ncVZTZ0w5UFk1
        YjA4Qk1neURKZzJmdzlEQ0Zld0gzS3cKU2pzXQIUwLzMNJB758DkLG0FEDdgxpeM
        9m0TuBqxjut1SgwZBQWLxbyvLIbEEJF8TCkAapzeAknuIZHCToYW4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T02:45:25Z"
  mac: ENC[AES256_GCM,data:YiC7LLmZiRQxACFXXW8PhGjg7Pge6HFyakLTwOVMvDcC9nKMDkD26ML6LfKxqXq2Tb1sSTnucoon7YQYU4URxeZrWceS0eUlh+4AChZkcW0Aj59faHlMaldWLnLziAI1mq52SCDuUdFr+o4kFHakKy7flms3VBvffy7XEV855wc=,iv:cJC9HNG1smgqK1ZAzi5vXpQfW6D79skmpYU0Qn6sUmU=,tag:PSRt5kHxpLHCK0PFI//DvQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
