apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:PMU9dwdoxSaEkBQ2KIqZiAFNwIRu9KniGGA5LsqGLZg=,iv:5wwYnFfRSoWKZYCejDOJZisCXGxFhBu6d0SZVwAd6xs=,tag:oAjR5iGkXWQ9xKYxu/VIKQ==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiM3pBRVRxUnljaHRmT1RX
        bk9vZG5ad2R2T1BaYWVhQnBYRXd2N0Q3MmhFCmE4OXlCRUIvQUdxL0NtbGNiVTV3
        V3BBbyszc3JqOVlPMC9iTDlpam5QNzQKLS0tIFNEcjNReTQvZHJNeDBFS2lEODAy
        MFNEdndvN2lXamd1TGJlR1B1aVlVcWsKK+vaBR2zLeXJhl7AGlgst0zxaCuGtbvE
        031JHDygyq56J+ksC+U7rg8UGU/uLbJCGheQKxdwAEhIRzGRNtx+BQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T01:13:07Z"
  mac: ENC[AES256_GCM,data:Bh9wIY1o8bQfqmW/SFuHut3X2XDavq/JoF6YooXdVuZIgxIbRUy9KHv1rN08F/DTQRuZbcE6z/0U9QD0YdA25cS2f9eDLywAEEGX2sL4Y1iFFhvtO7l+ElSgWIURrBwVIv6QFqgwV6mZ/sul00P98AtIrSWDgtCXvKPodP6bNKU=,iv:utTyE1+GQsWurU0c9muVqQNS5JTSkfg3bujJ+xG3BvU=,tag:ta+R0QIaL4uJrb/PSOHM6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
