# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
  namespace: observability
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:BAZ6njE4z4KDvlTx0H2dTlq+cdfpCWwhCqo3UJT3mco=,iv:V6oqRoHeB/GKedT3QXqMy0XW94j0DRBy0G2EcDf/5C0=,tag:ojBWlFcaHGrbw9URMsBPYw==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZXgyV1huZFROc1RGTDZB
        UjdmdmlqdWdqMm9iQ01yTE1KVkR6cnF2dFdnCjQzeHdXOHpYWXRqemFvbFkxaVFS
        NmhKWnRvVkpxZ2ttQk10aERiOU1NVFEKLS0tIHluME5pbFJOQWVSTURicC81a1c2
        Z1Jadk54MFB6S3o5Yk5QVTl1dmNteUkKEI1NoWmv7XPkp7C8m6m6WIT6Hchqrcj7
        TsjsXXAWQBAUf56JdEBMA7nh9QGxe3JP2JJABwBvJ/Xyj9tmcU5pYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-04T02:52:47Z"
  mac: ENC[AES256_GCM,data:TZCr1g7dM7lR95ABXf37bk3cEtGe6pviXSjp7fzoUf4h9QpdjwcSz/Msu7GRXk5qe6RigwovjrcjCDsS7MTTqgi69sRrBHfg4Mwwcs/kjguUFV259zog1K4avgCaTKCFmoae3Ceozi+O/2HYWZAC59Z2JgsRl49mOGUEsOky1D4=,iv:joOZYkzGqZzx8t4tV0WCD5im+rHNEDXAH8Hn2bzJ3NY=,tag:JSDHYn33F/Lc1UqaVWJ29g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
