---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./node-red/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  # - ./zwave-js-ui/ks.yaml
