---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/alerts
  - ../../components/common

resources:
  - ./namespace.yaml
  - ./agregarr/ks.yaml
  - ./echo/ks.yaml
  - ./homepage/ks.yaml
  - ./maintainerr/ks.yaml
  - ./plex/ks.yaml
  - ./seerr/ks.yaml
  - ./tautulli/ks.yaml
  - ./wizarr/ks.yaml
