apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:X/qXYbMzGrYO6HsqddztsOgI0y1rXZEFUu2SFUejogGzosfk5Oi1Lvb56/361ZxdHXrsU2YSOwPmkEKSpz8wrLgBNni3OxRcq/br+7ddXINTYkn4GQmNMaUiATjYhSOFuze2C/YShKJzLQY6+ZqZ/9dD+qdtFbxYMH0Rhxjg9te2cx59yM6MoUZL4NaJUfpE/KrkHR9MzFDftFVBqGPXnwKomwYetXBpTV9a+FW6Ieyhmn8q,iv:4z3QMsOPjjORDuAIO98nf4d4eX4/eeSrPQ/A0Wpi9x0=,tag:KSZ6TpR7xtuL4V9sKb8vNw==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYN25wcDNIdkNWOVliMFQ5
        a0swaXhrSDIwZnd4YmZYTkljdmlaSFBrUVNrCnlKV3JYQVZReWNaM21iUStqLzFl
        UHZYNm1Ca3haSkRnMHRZQUZJR1Q5YmMKLS0tIERacERYMXVmUnZHNXJCZExDR3BE
        OS9rbGI2UmlubElQQmMza2Vpcnl6VWcKU/KV4Ine8Go037VGMQHAPVNscj/7/Uit
        FsTXYZQoRIe3EaFB4J6EbgHxlkFxZggImnbcwAat0zH03E9cOuqsJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T01:13:07Z"
  mac: ENC[AES256_GCM,data:YJM50PH4kt0t8yZzlAYXwt5tMzDeSHFJ9pQ/jql7ZoCg17YJnvzr/D/m+UMKKg17um0DlIEz1LxSqVylqxnfEQynieW78Q4G185FzDcwOoxKOC7iKgGur3olPrXLg2YhpNvXE3j+nVIwLZdd1sfXpRjbItKNswX1CAvFkYseelQ=,iv:DPBMCCiC+vbbQrtGPcNcPylh4twSKFHa0ipvTDk0Z1Q=,tag:pDWzS0ZLBUhTA2C7IkwlDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
