apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:eA7V9vH290S509djyYRzYLUjdp5Whi63YovSENHrubYGAbHf+JmfADyU75ziyQNisv9LJSoCJ3XbW+3NKuClVLUmvfkQRFGYYsEkDA9so41xZYqemWT6kMJEEyrzsbVIAk7l0vFLtpn2Hu0fFMXcKx2xYMij2c8LggU1Djm88kmUbTU3yqa6DG6C7+iT7AWd3lkaozeYcdBIL8/PJG4uGbnqyGE3K9+RjCKcMTg53vdIAHof,iv:IhzipbdGTafHPSb6k4IhX1SMmqIE58LIri7JSMDzodA=,tag:jnPvb/8JSAW6L7GR6GKpDg==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NUFGQ3I5d3BWcThXeC9V
        OVBHRVVIWVRjRTZiNTh0V09sZlNyU3R5UjM4CldLbjF3Zk1VcUYwMERIQk1DaW1O
        b2NRMjBHdDB3ZXg3QzNtYTA2TzBtUkEKLS0tIDI0SlRkcXpxUjdhSzRpQmU3c0xn
        OUVtU1FZVGxYLyttTWI2eGlRNEREU3cKPWi6e+AIdHDTEaAR3LVazNupUGAzmUYA
        anH9QSfG6VkuwZqMLoH1gwLM++gAvbCJjzkF4nXLXZYAqBwkD7HCgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T21:27:22Z"
  mac: ENC[AES256_GCM,data:3CJU7Khz1b2q9iKnf95E0FyLsDbf63BZ+SvuaFVmbei0t2UAccJEacypD/wy8ihkaVbm8jxlH/0plKiOjIWit5uthpzF5ol8OJzb9kJD2/Ze9n1FYZunkeM0WaP/kgFpnRUpylcvAl2GvpsZ+/ckJE22WLbfj0rM7lDoRu2AHXQ=,iv:JKPx7Uww/nkWiQCCsEGH6o1Pt4cVCbg1GDoU7SnwB8E=,tag:V8HVZNUsdMh66QU41fQtfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
