apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:irLS8pMR0k6S2VJc7gDU5vXdc8jArcBRvi0ViBfyF3wXlCUGluYWd/VEmNyA+hO45iMlCnPU31mEY0lsIXso7ikGSu9uSqP6ZfgBxRyRBbBzxJKFsEjqWsuTopvjObDmr/v6ylSmRoiFKs7vv8Xy+WqrA3BDNQrn6URMWh4+sim7wKrldgCzHj4zEr4hNTzNrkaH4mMYNw+xlGrL3ahOTiT8AMVmM/qNxze0FlECRPrAy38e,iv:kUx1Be1kzZECJV3Op1MjENjWhweaqI6rl1Xk2SwMQt0=,tag:8SeTuKx6JTN1JT4smP5AgQ==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVGI2Y1pQcjFIU1pMOXc3
        bFNjVnd0WUJSd3lHN0RPa1FQenh6VnVTMmlzCkQ2UWdIQUJxSExwR0t3WFBkVEdm
        WWtBckRwMjhWVGZzT0hLU004MmppMUEKLS0tIE1DT1dmYXVJWWlZUHQ4L28rWnNw
        STVPcTJiNFRySEpBOGZNYVE5MnJSWE0KqCT702T70dGpJjud/VoScK2kRgKeWxqi
        aEZcKRg0R01qdQGojybYX5bkGjytDf5GxXv2v1j3WmzDSTTdzw4C3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T02:45:25Z"
  mac: ENC[AES256_GCM,data:hfM0vnBFiqOsuNalXWGTuUeSvVitNUeNvKRshc4FzHe2R0ic9C02WppLPvGUxfpWwzZjwedFxO1gsJZHrlBYemqFgzQnpnBbKjLBz4tFviQAgKLWyjfq63ou0zOouGWX+dJb2HCRbBIB0Br5FJk8vSDpvOwkSMidu9b3A2bo05o=,iv:7CTpefoLGxCPh8+nIDH7Sb34RLRVSKbiaPnMxS0FQ9Q=,tag:b+nq/T+bJqhW0wi1FXeaVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
