# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
  namespace: network
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:85BdzJyCW7DX0DWo28XW5uQYmQ19s/nsAQBn8lFUxDI=,iv:dN737XOTecZF08q4UA9GWme0a3WLRnwcR32y4HgJ9A8=,tag:vH/Zs1ylXV0gO2IEKt0xVQ==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQVQ5UjVHS1F3VzIxNStH
        SGlxV3lZeEVuNG53MWdMVi8xUUkzZFdwNVhrCjNHMXdYNmE3NFlHV1NTUyswZERs
        UDlwZG5KdWh3S1BORkJiN3ZPQjJwVWMKLS0tIGJrVzNNalFiVVJmTkYvcGhlbUE3
        Y3hBWlNPaWpFSUVjeExQRThrWHI4MjAKY0B93iiltQjUnzvs7L1d7BktO3XkJ3Qr
        dGyzyzeNWmMWcTzJ5e/pAzutucvyQqhvky97rsPFtQE1geh5gEISLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-15T02:42:23Z"
  mac: ENC[AES256_GCM,data:nqRl513TACXf4vhH9Te9kcKgH6OyAdhBSSMyX7qtLfcFDlVFy98tpa8bn0wzEem/w9NHF6J79RxhgzB4LKEtj4cyEft/jdWE+I2pHKGLYl1GxCWRg/8xef35lcJ4ZcDY0TBLnHtfjHEEhKfQ0rhM46Fpomsbau+8Za7FJAxpcLs=,iv:/vYTqIbsCKsXxXkUzwfn9oAc5b/nevrTpCSHMUA8Bps=,tag:R98I4q2/W5dgndz4L8F7TA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
