# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
  namespace: network
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:85BdzJyCW7DX0DWo28XW5uQYmQ19s/nsAQBn8lFUxDI=,iv:dN737XOTecZF08q4UA9GWme0a3WLRnwcR32y4HgJ9A8=,tag:vH/Zs1ylXV0gO2IEKt0xVQ==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQVQ5UjVHS1F3VzIxNStH
        SGlxV3lZeEVuNG53MWdMVi8xUUkzZFdwNVhrCjNHMXdYNmE3NFlHV1NTUyswZERs
        UDlwZG5KdWh3S1BORkJiN3ZPQjJwVWMKLS0tIGJrVzNNalFiVVJmTkYvcGhlbUE3
        Y3hBWlNPaWpFSUVjeExQRThrWHI4MjAKY0B93iiltQjUnzvs7L1d7BktO3XkJ3Qr
        dGyzyzeNWmMWcTzJ5e/pAzutucvyQqhvky97rsPFtQE1geh5gEISLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-15T02:24:45Z"
  mac: ENC[AES256_GCM,data:8r5iu6hQReTUubuk8k/P0P5aZydqHFL5msdD8VHP5YxjY0t8Adcrlb2aOkCooTFeeBx+jY8NmxigMXo3EnD1DVATXBsLfHXg7BDPPbyFVdPXC86frU9iyBsH6ykTzyNTfb53JGstvX/eMnNLczjvG7EqfN/UCVYKwimCPN6vLOY=,iv:6s5NvwidYViuqMJbYE8VcoY5F4iK9IxUiPkEuyTAJpA=,tag:lLG3Z3dWK5YNC7zUAT+D2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
