# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: seerr-secret
  namespace: default
stringData:
  API_KEY: ENC[AES256_GCM,data:CuO3CCOqeqClVWcbcpJvRuA6/1zipAMr0szEvcbqWoh28+LfJYggMl+4uPKJ2tV3Ltf1vTdxyvJI4PvvaWbjJXM8qVs=,iv:aDm6V52COAC8RiEmDdlfQzYmkB2UuC97dMv2GdVQjp0=,tag:DOB9JQoPkmS6a0SFAdEETQ==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MEdaOUp0Q1gwUVk2aUE1
        TW52Y2FkV2czZGdOeWVIUkVhcml4NzFYZkMwCkkvVkV1L3kvbVZMeVZlaHRvYk1B
        K0FLZnMzQ0xjMHJlL1VtOUZHK0hoN2MKLS0tIERIa1oyckM1VUFqTkZDV01WcVpZ
        WWI3aVFENzRKNnFYMjIvb0QyMHNTN00KSoeOmDbIJ6WCcKqQEQiM/vJoD3ao7beJ
        RNGRBDMox/g13WMi6Kf7a/O0SJWEDi7uFkgP6z70P7YF6/9i92WrLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T16:08:13Z"
  mac: ENC[AES256_GCM,data:ZpfzjW6I1zKNA5N0bvtZPplpiaeE/seLn/aVh+Xs0uMV44ZMkrID7F00dyc+GTr2SBI5WPquUAYn+0ObNfhSt0wsfXKMEx4j+zqhLh6QxAhp54nPtRKqStamjLr0yv1IxkJ5wrpmvJEUxkMVi1QIQpbUqwB4sTkYgipu/SxaBMs=,iv:U1lA1w1TT+BaF02J7X7OIFf3VKALNWmYUYrKbxlRwSk=,tag:SZJS+aX741B9648Qi+zOTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
