apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:EwgkOyEDqAVMN72XMs7V+iY9v49uurd+rwwhvN0uoQhe8frs/0gRAg==,iv:iApKKxUepnQ+RRDvxkzkUu9OEFzApHSYH2CLNtCc7i8=,tag:kmvpTl30RgLChOuFpt+Z1A==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Z0wwZjMvQmk2MzZlVXhO
        RDdnOEhiY21lRjNIeFRHWWpuWUhJbnprRGlRCkIycFdBTUdlNVhISDByMGdqWjN4
        VWZubXZybkVLWXRWSDdLQVJjV2VIK3cKLS0tIHlKVTdDYUZGZUhFd1JOMkVERTY1
        Ky9CWXZxMk9mcW8wWXR2ME9yMWZtL3MKEjsHLVib0K3xcZRwPxClXnrDKPWKiTWC
        pMOlNqsZgnvmIu/e9Rots6z2sAqoyIvZJwAOMkLpxZ52aCb5mvVzoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T02:45:25Z"
  mac: ENC[AES256_GCM,data:thFuDeK/9x2tDginCBzXtlnS0mTkWhFoiKIb9Bit6JvQTkOMQJBIiXHMViX0Lrt3Wzcw0yT5ngebF9F4JjHsgXQWmjiSpt/3c9nNvuYAKvOk3XMm7i2v487FBDD4Rh4BusZ4P21oBNXl6oLSgAd7Qbpq6TJegGJhFW9S17SZtbs=,iv:n9tr6RImGxoD8gf4FqlDrZInhpJFQ3D8MXId0R+EH/g=,tag:21CdcRtaoLNuDfgW8GF44w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
