# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:WX/z52EAeoD1rR8=,iv:M0Ao8TFFFpJ4N2DLaz7ASdP0tfceZkz1xtZIhuTnWOc=,tag:91/YMM7gRWhKldchR4WDGA==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:WxAm0ibBTSHiJZdP/LM0G+z15G9+d6ZXfrOersrGJ5wYQbCyOzyX/jdsEOQUolph,iv:Pnrc2j8oxDoVcCMzAkGLJhDoZdoQ4huBxV+lxO1El+0=,tag:yBNHJEd9w1WsKlLbE/3FhA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:d7IgmZQcZowtTNgQ0PJRCqsQusrL1SLj,iv:79V7Qu6+qrQg3pKACzgnh2YnQ4S9S+n4Jm970RFFYvA=,tag:oH1gT7V5p62QCp+f7mxwoQ==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VjAwbEthUkl5VmtET0cy
        VmxwSG5NNkdVRnJ0djJWcWIvS3hPWDhLckhVClB2UlNEczVDL2tEV0hiT2hOOW5X
        YWZtWDA2dHArMHZRNEhUbzJSZTdCRFEKLS0tIDQ3RzBhQ1ZUNThLQ2Rxa1RYZjhw
        Vkl2UzBYOFNYbXdGRWpmR1lFTEk3dEUKp2iR/gUC/wzhd9V54fqQc7BrQFncgaas
        dh+xm+1sEzYVY5gg+IkXQhCW1qlIQ3/R2RyE5+sLPovFMW9Gu4czog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-18T23:24:44Z"
  mac: ENC[AES256_GCM,data:9hwnVdB+ftaKD6JBXM4CuJ0+nkEDttUhAJ5+8Q5Zi+a1bHLYx4QB0AZMw7cJO74K5oy2gKVh9WtqRTBHwBygMUQUAg+crV7nh0MCc5mbzrd2en2krOAgtJtl0FmTge+H0KLOdSGZ9E450XZZGPDYBwHhSIAPoLoENB4W6ZcHxSQ=,iv:gtn0loYT+PwgEeyuVE4Bb/82cNWR3E9R8ECvXQ09wZQ=,tag:XgYmwcGk8Q1Uth859fFfuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
