---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: zigbee
  namespace: home
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: zigbee
  timeout:
    http:
      requestTimeout: 0s  # Disable timeout for WebSocket connections
