---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./backendtrafficpolicy.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  # - ./scaledobject.yaml
  - ./secret.sops.yaml
