apiVersion: v1
kind: Secret
metadata:
  name: zigbee
stringData:
  ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:T3nWu8dobhXdVXP7yNkd90MeaNpDBASTUpyEH3A=,iv:14onCAlce8ge7GqLNSt2o68znwEuJEOLYEVqhF5i8Sw=,tag:St8xLlvSJkJ0KI5oxpiKDQ==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:cyEx5xA=,iv:q2ly2RUrZ/RAGqglnXhf9RMpAwMpUmZPWUxcJyiSrVE=,tag:1V3YTRnM8UjN5ifnuZjIFw==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:jKaLqHKcHHeIPJL/+6BbQajcU3f5vN0oIMjGA7RFxdUEJp2Nc60+aLCLkRZBf2RWGr7K5GIs1wHr,iv:jQDHV1kW0qfpsq7/VsGye7b+EuIxi+imeNw9O69OmaY=,tag:jIlNmrO+pOmaGX02Awg1KA==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V1ZGRGZVUms1UDhCQ2lI
        MSt0ditHQlpkR0w3NFBWRmpRdTZiSEEvSWlnCnFoN0RKdmZiMXlmLzFOVVBhTGFy
        UGNDM0hBY2UyNXVmY3ZKQUJsK1hhU1kKLS0tIFZXYnRkcHExK0lKTHg5emZyUXdp
        VWp4R09XVU5BREVaTFRHR0l5Vi8wRHMKyUrk/fr7AoXTGYZhVnh6L89DNfNtVYGF
        5Fy9ICWj9wCXegDpb0czfFdNreuEyluxDsm16acLnKDwIJ9KoXgZbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T14:58:12Z"
  mac: ENC[AES256_GCM,data:wXnYxNMVUi/fIjpmyASSnE/lTt7Ir83XWBCHm+tKVcsTu4J8GCxXFNH1aXbOSQ8B6gxGiabHv5GToa+BB3Kq219K4ZFH9qfnol+fSsS1LKm0TnHxM5HIMmt3uYr4YxmUOEcwzTaveelFcSfKQhnuQjnOOo6arFJEn38Lqpkv7bY=,iv:i6RG8bUyR7TfhEorU/yO2iGEESDNUGIiUbWEgAEGpoE=,tag:YSvz7BnR5RoWapuJYngLAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
