apiVersion: v1
kind: Secret
metadata:
  name: zigbee
stringData:
  ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:+6jQSkXLOkE=,iv:yvPDxqAvpystfKEBNSVQajIyVkc1izbo2EUMnAo950U=,tag:1kpXP/O3tRmKUAQ8kHuW/w==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:f6umT5U5TK4=,iv:sydHMY+9lg6n702MIX1iPEO725nYSbjlgyVvLWRvSnQ=,tag:nes4XOXbAQIjeoLcvnGnjA==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:QkuYUhoeiO4=,iv:hx20Pzb7SuPizEUPl8qglQylnMBuYvQIynmMGlAm0M4=,tag:31p56oZKPA6z/Ap2TMUP7Q==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V1ZGRGZVUms1UDhCQ2lI
        MSt0ditHQlpkR0w3NFBWRmpRdTZiSEEvSWlnCnFoN0RKdmZiMXlmLzFOVVBhTGFy
        UGNDM0hBY2UyNXVmY3ZKQUJsK1hhU1kKLS0tIFZXYnRkcHExK0lKTHg5emZyUXdp
        VWp4R09XVU5BREVaTFRHR0l5Vi8wRHMKyUrk/fr7AoXTGYZhVnh6L89DNfNtVYGF
        5Fy9ICWj9wCXegDpb0czfFdNreuEyluxDsm16acLnKDwIJ9KoXgZbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T19:57:34Z"
  mac: ENC[AES256_GCM,data:AZhDuh+mYtuqbuf8efEd/ZOfAFdOS4urC5IkFTlnDteN9u17anAdHEPu8EkwoQpxtz6grbn0X7ZfGAsD7C8RxChY08qoJc1adAsm2VxaVRyfefnYRIl8aXYmAEEv9n+aGxM9X19kxBK/EFmy5HOeGHJfngZUilWzR/qwMkk3vPE=,iv:XOV0l5zhmBtE/gzHzQePGvXPljXyqmGycvbYAMJX6E8=,tag:8S2TteIELP8G5XR8ZSrTng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
