apiVersion: v1
kind: Secret
metadata:
  name: zigbee
stringData:
  ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:T3nWu8dobhXdVXP7yNkd90MeaNpDBASTUpyEH3A=,iv:14onCAlce8ge7GqLNSt2o68znwEuJEOLYEVqhF5i8Sw=,tag:St8xLlvSJkJ0KI5oxpiKDQ==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:Kv6ktYc=,iv:j6okC+aDIxUPLAV4dSvkrKXXqw8a3FmXUZ49ZalZ9FQ=,tag:cbtn5xWeWkmG0F9ZNTLFBQ==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:jKaLqHKcHHeIPJL/+6BbQajcU3f5vN0oIMjGA7RFxdUEJp2Nc60+aLCLkRZBf2RWGr7K5GIs1wHr,iv:jQDHV1kW0qfpsq7/VsGye7b+EuIxi+imeNw9O69OmaY=,tag:jIlNmrO+pOmaGX02Awg1KA==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V1ZGRGZVUms1UDhCQ2lI
        MSt0ditHQlpkR0w3NFBWRmpRdTZiSEEvSWlnCnFoN0RKdmZiMXlmLzFOVVBhTGFy
        UGNDM0hBY2UyNXVmY3ZKQUJsK1hhU1kKLS0tIFZXYnRkcHExK0lKTHg5emZyUXdp
        VWp4R09XVU5BREVaTFRHR0l5Vi8wRHMKyUrk/fr7AoXTGYZhVnh6L89DNfNtVYGF
        5Fy9ICWj9wCXegDpb0czfFdNreuEyluxDsm16acLnKDwIJ9KoXgZbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-22T16:13:15Z"
  mac: ENC[AES256_GCM,data:h1jhhbjhcVz28i8kxsWN4+kAbgC3/DDePrc7Ga3U7vEDk4Z/QbEYa36nqykW/HgK2DijL0aGzEAVNZxkH3zvRF9bd/POWFvuFbjXB8uw03EvT7/DEAOzQXMaIvaqU9GjpEoCrXx7a0OsBexwJCTmdmlkm5JvhOoqUmHCSVtJgEY=,iv:QSVXiv0Et9cEyyh7uwv7c3NnM2X+VIqhuIng0KcD9A0=,tag:5/Y8RXlm7c2tXVxJPqcf5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
