apiVersion: v1
kind: Secret
metadata:
  name: zigbee
stringData:
  ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:T3nWu8dobhXdVXP7yNkd90MeaNpDBASTUpyEH3A=,iv:14onCAlce8ge7GqLNSt2o68znwEuJEOLYEVqhF5i8Sw=,tag:St8xLlvSJkJ0KI5oxpiKDQ==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:cyEx5xA=,iv:q2ly2RUrZ/RAGqglnXhf9RMpAwMpUmZPWUxcJyiSrVE=,tag:1V3YTRnM8UjN5ifnuZjIFw==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:jKaLqHKcHHeIPJL/+6BbQajcU3f5vN0oIMjGA7RFxdUEJp2Nc60+aLCLkRZBf2RWGr7K5GIs1wHr,iv:jQDHV1kW0qfpsq7/VsGye7b+EuIxi+imeNw9O69OmaY=,tag:jIlNmrO+pOmaGX02Awg1KA==,type:str]
  ZIGBEE2MQTT_FRONTEND_AUTH_TOKEN: ENC[AES256_GCM,data:Fn+GJHPSW6jwzYcL5wWQL/P1pSNn/AjHGWTsVoYnfyR/MYOjV08mtXNErE5HxmZRiw4f4d8zq8iFUIhFAH6I9g==,iv:KBxQK+imCV7vqnq/cHTGBvbR/4MAQr0R+1ZHzhI7mpE=,tag:LoKLkHTMWjpQeAIviIha1g==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V1ZGRGZVUms1UDhCQ2lI
        MSt0ditHQlpkR0w3NFBWRmpRdTZiSEEvSWlnCnFoN0RKdmZiMXlmLzFOVVBhTGFy
        UGNDM0hBY2UyNXVmY3ZKQUJsK1hhU1kKLS0tIFZXYnRkcHExK0lKTHg5emZyUXdp
        VWp4R09XVU5BREVaTFRHR0l5Vi8wRHMKyUrk/fr7AoXTGYZhVnh6L89DNfNtVYGF
        5Fy9ICWj9wCXegDpb0czfFdNreuEyluxDsm16acLnKDwIJ9KoXgZbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-22T01:35:45Z"
  mac: ENC[AES256_GCM,data:dIX6y6Dltczz3uXWmwu7cpWtjomTyXR1ZBAsxKs70bsQ6H2NtJaDzmDQ1v/t7dffA1MfS95o85D4S/cJhkjoHDN+vma+7yR4VFtC7opgm+uz58oyTa9nNMqT6lzeu8tsH1PyMMsxprA9DflbmFYfS0iEupLdQ3v+Fe4hM0d3jEQ=,iv:zYdc39qEsvw8oKBmJjYD1aEmkP2CMb6djqQYyM1qTs8=,tag:63u9CqVO7zN/4ywH3aDw7A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
