apiVersion: v1
kind: Secret
metadata:
  name: zigbee
stringData:
  ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:eBchKHP2k6dNotJ+o6DEwI/Ib8AmfPea/s3x0XYUbiADxYlhrRCryYxSxXB5juAyQIbGGv5W6D2O,iv:YNMI80uLz8/AnCRNVb3D7T2SJ/zYmmGVd+YaWtI+vQ4=,tag:wD8wDit0KHz8LVj99xrnGA==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:xdth4Zs5,iv:V8DiUlhv+dFomInxeyo18Ta67tqacG0cjuD7bsrldpo=,tag:oyhu6Kqc/fPBJ8JZMwjaig==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:DAxnGexBNdtZYbJnnLOQnSviGq9syi7EyaQWDdE=,iv:Z9AsNmU2vd4JLqNtr87OejqBevOz9CCp1mXlm2aiN/g=,tag:IuxIjJDLxEDSCWLMrlebzg==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V1ZGRGZVUms1UDhCQ2lI
        MSt0ditHQlpkR0w3NFBWRmpRdTZiSEEvSWlnCnFoN0RKdmZiMXlmLzFOVVBhTGFy
        UGNDM0hBY2UyNXVmY3ZKQUJsK1hhU1kKLS0tIFZXYnRkcHExK0lKTHg5emZyUXdp
        VWp4R09XVU5BREVaTFRHR0l5Vi8wRHMKyUrk/fr7AoXTGYZhVnh6L89DNfNtVYGF
        5Fy9ICWj9wCXegDpb0czfFdNreuEyluxDsm16acLnKDwIJ9KoXgZbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T14:33:12Z"
  mac: ENC[AES256_GCM,data:a0WYjedox0OPcG9g/8D2SYxRdW8dLSy/PqAsoEkCvd4OhSelWyQhV5nB1aBQCNSWp3LIgfeu3Vepdxb/gQdI5R4X1Qev/NQ32Z3vS4ou8KLNM5paOBI6I5DkaiL2e875Rsgp8QQo1V6r21ERHf+9uaX/Uv/Z7N1WcjVWT8vV+0M=,iv:FV7PmLLyzDrhbJyGj3dqC0aV6ZCXFv3ly5wIOS8lTSU=,tag:EdH/Lqkgm3BXMVhAHiXdyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
