apiVersion: v1
kind: Secret
metadata:
  name: zigbee
stringData:
  ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:T3nWu8dobhXdVXP7yNkd90MeaNpDBASTUpyEH3A=,iv:14onCAlce8ge7GqLNSt2o68znwEuJEOLYEVqhF5i8Sw=,tag:St8xLlvSJkJ0KI5oxpiKDQ==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:BMToSWE=,iv:0QjohRoBEYXQKudvtQABRJWw514lVgwUaImAVAMNwUM=,tag:y9yKB9nRQCI03hU+9zFmVQ==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:jKaLqHKcHHeIPJL/+6BbQajcU3f5vN0oIMjGA7RFxdUEJp2Nc60+aLCLkRZBf2RWGr7K5GIs1wHr,iv:jQDHV1kW0qfpsq7/VsGye7b+EuIxi+imeNw9O69OmaY=,tag:jIlNmrO+pOmaGX02Awg1KA==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V1ZGRGZVUms1UDhCQ2lI
        MSt0ditHQlpkR0w3NFBWRmpRdTZiSEEvSWlnCnFoN0RKdmZiMXlmLzFOVVBhTGFy
        UGNDM0hBY2UyNXVmY3ZKQUJsK1hhU1kKLS0tIFZXYnRkcHExK0lKTHg5emZyUXdp
        VWp4R09XVU5BREVaTFRHR0l5Vi8wRHMKyUrk/fr7AoXTGYZhVnh6L89DNfNtVYGF
        5Fy9ICWj9wCXegDpb0czfFdNreuEyluxDsm16acLnKDwIJ9KoXgZbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-22T16:31:06Z"
  mac: ENC[AES256_GCM,data:XwBsqYTRGxzRuAJhkW/eHl1tTmqw4S3UzzHdrzV5G/WorYa9q2+eeIWyFu3wwaIa7MFZcx/mhJHK5ox5yY/waWT4xoS264NZrQa3bKEGQ97ci7s+N1Vz3WFcbZqEp5+Iz8vOpAtheyikR79+++mfSY3m//AJDGhvS5jGO1DW0Os=,iv:wFcDw5LwbtDNnpx6aYqgBCRlTmZlym2KBVP48Mugvdg=,tag:mXChIRadvsj8ENZQcxtS4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
