apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt
stringData:
  ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:cdjNsyJj,iv:xtMSKe273iIYlyBwhNPd7lNLeOzNPsep77ruy6k0L6Y=,tag:wz4j4f3y4TV+D/Pfw1YQ9Q==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:O7j6Ri3DMqauGYU1dsFAsFaGBIFbmDc=,iv:bnUNw9x3zUzh2vVNsqHk3hNIeAHV4TlLuJ3+mZdFhpw=,tag:uGac+ZHW52RWopxWc2Y//w==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:BfO3sIZV80EiBPWqC19b0CCV59PKy/NoRoLH5SIylPm7bi1ikz8u6/u34OAH9D0=,iv:Z9FIJ4291ueTNtu9wZSHWw99BOmABVVFuIiueC/UFzc=,tag:oQoKvmwJBlmWl83QOhS0OA==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V1ZGRGZVUms1UDhCQ2lI
        MSt0ditHQlpkR0w3NFBWRmpRdTZiSEEvSWlnCnFoN0RKdmZiMXlmLzFOVVBhTGFy
        UGNDM0hBY2UyNXVmY3ZKQUJsK1hhU1kKLS0tIFZXYnRkcHExK0lKTHg5emZyUXdp
        VWp4R09XVU5BREVaTFRHR0l5Vi8wRHMKyUrk/fr7AoXTGYZhVnh6L89DNfNtVYGF
        5Fy9ICWj9wCXegDpb0czfFdNreuEyluxDsm16acLnKDwIJ9KoXgZbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T16:50:17Z"
  mac: ENC[AES256_GCM,data:rscZc7fIqIU75lwv4Lb0/mv7ceFQXwC5Nv5PUPGWpbtdDN50FA3ZJ1xTmvsL5kiwqR1zHSfIE2W7SjCgr6NTdQBKJBPsVoB/CDVdSodItA18bC2llt8I7SwVJ3gUwCXn6w+ewIziqo8wfQtikHwMYfwvXKvXPUgvbuWrRFGU3R8=,iv:zWtjAgr02HC0sOClsICft91oYb9uZZm3qUj95HiAkjc=,tag:fryxNlbGe8xN2TVr3iAC0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
