apiVersion: v1
kind: Secret
metadata:
  name: zigbee
stringData:
  ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID:
    - ENC[AES256_GCM,data:L05F,iv:NeRAc+nJ0fsepQ8glDVMVroRrSOekiXWCF9wgQB86ss=,tag:u2gcWVKyG8oj2Q51tJMiKA==,type:int]
    - ENC[AES256_GCM,data:5Yw=,iv:Dp/7Z6tRxIDxV6vkb7uJiMYEDC6nswkss7iPP4kMp9o=,tag:jpPpd0LuC4J/ET6LNTAthw==,type:int]
    - ENC[AES256_GCM,data:boUK,iv:idJGunStjwVOYF8RVw3V8yvdTG1GDXtfGwfMQOzvoME=,tag:juXKkgycs7I/ZwPLvq5VKg==,type:int]
    - ENC[AES256_GCM,data:iz3E,iv:5DghLUwkn3E2DQLkCiqnWjakl06xy2LXInDRqhIbSIo=,tag:DRAsoISynsSom+E1yEik+w==,type:int]
    - ENC[AES256_GCM,data:nBV7,iv:T0MCSTZ2ciPd72RlyGsUB0qJtXHoU6WcZo2cNmtrk78=,tag:xKOxGT8xCQNaq94NINo6HA==,type:int]
    - ENC[AES256_GCM,data:vU5h,iv:iHWR8T87RSkLqP6/dUQ65NzMvU0NF01RmYxcTMYw8sw=,tag:2bV/eQzLRAk9ndKyBC2f4w==,type:int]
    - ENC[AES256_GCM,data:Pg==,iv:rY77qoa4rSTs6OBajEBIvBeVlQVvVmSj7C4kQ9t2Pv4=,tag:6LlusuT7BXUKJ8pfIHOJAA==,type:int]
    - ENC[AES256_GCM,data:vX59,iv:6FVOkayn3SaVuavsI874/bRoOIGc9TiiiLGI6I3LTfU=,tag:kuwlcqNMManJKe0I5gAF1w==,type:int]
    - ENC[AES256_GCM,data:FluS,iv:CSoadvLVe8QIqTVjncoQnEuPVuhOI0ZkBNNXz+yLuas=,tag:zBuTN0JIkUpJHvPybSfYMA==,type:int]
    - ENC[AES256_GCM,data:nXQ=,iv:JUOSSGT9Os8iha94rHnynG57y8AT9kN+Tb5gfK2m6jI=,tag:3wKpglhgC1hM+mOF482QsA==,type:int]
    - ENC[AES256_GCM,data:ESN7,iv:46Q+JNj8pFmG3oLi+T8LitCheEtfc9nfUsW1P0V4tjs=,tag:AFI8+ikbk42UTjvrrAvAVg==,type:int]
    - ENC[AES256_GCM,data:JcQr,iv:X9uteFwIBACptY6HJXWTz13NBNUmA272+yuNbtB4yRI=,tag:fckQ0k655uAnx1+apdfNYQ==,type:int]
    - ENC[AES256_GCM,data:RVrT,iv:N9enEsadVh6iP52H/udyxa5jXgaXe9kkLJDmqduCo2Q=,tag:rDK/jjdSeKgzFZ7+k6E8zA==,type:int]
    - ENC[AES256_GCM,data:sg==,iv:2LAOuRJXo0cx9OPfV7lJ6ZjkPv9JArJmdOCLbKPZgX0=,tag:4tlF2R4NbDwhIQJETEC27A==,type:int]
    - ENC[AES256_GCM,data:uQ==,iv:mBFKlVTqrPlTqgm+A/D0sQ0wVCN0SltL/Mg09FXK8RY=,tag:BWBShAoSPpd2usU9halThw==,type:int]
    - ENC[AES256_GCM,data:nh8b,iv:vJYRTAada4stPCFlU5p/V+HTe2e2qHeK86m32UhNLp4=,tag:xpmWrODA21tjVlK9JIelxA==,type:int]
  ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:IDPQpZA=,iv:sPdjfLI5/PLG93n4kyzZPbV4SUB57XEOai382npfkpo=,tag:aYQr+eOKI8tPvIUVmhgZIg==,type:int]
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY:
    - ENC[AES256_GCM,data:ODLs,iv:rB66T3T1wfgoS0Wb/+hA0mDjBGp11vZwFwkBtZTHxhM=,tag:Ltg9GC+8yva4Gwksai10Vg==,type:int]
    - ENC[AES256_GCM,data:AcI=,iv:v6nDrEbtXkln/8ChNapULR2lAyvunD9nM3jdSz4CCrE=,tag:8fXJ5GoxS47it7hZb1Xtpg==,type:int]
    - ENC[AES256_GCM,data:ph62,iv:Y+H2bcqWOQCB3gIsZc1uFMb/LqODQoYaDgTp7ky7Px0=,tag:nFvgmk+FwwOfyLvyf1w5qw==,type:int]
    - ENC[AES256_GCM,data:leJZ,iv:AynkD2FebE8GKT6whJkyYtQ+3nGWO7D9BAgXXYlnuOE=,tag:1i/qJ9LArnce7M7VRa0tAw==,type:int]
    - ENC[AES256_GCM,data:PrV2,iv:4/lMWDiZK9MMnsILRONk4D+SGMuhBiFb3laqmmGlO1s=,tag:0CxoUII3TZCAdRF4/BPO9g==,type:int]
    - ENC[AES256_GCM,data:fWY=,iv:23Gv+jKDelaC8eWmeIAa6Bohfc2ctogPzZvy2LsSl+s=,tag:lSUnWPlJaruS2cyVp5Nzxg==,type:int]
    - ENC[AES256_GCM,data:iXQ=,iv:TcUPJSAz4NSpK1I/VQ6NA7h9iqRPAxmJqIt8OVLdHII=,tag:6TcikQnda1F99CE5sEPjlQ==,type:int]
    - ENC[AES256_GCM,data:G80=,iv:y9shJDPAx0S0gkcoEEu94uorA4JY+OnQ25+pjzdyWlY=,tag:mZT+5zYs/rf1Eda6PcC7eA==,type:int]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V1ZGRGZVUms1UDhCQ2lI
        MSt0ditHQlpkR0w3NFBWRmpRdTZiSEEvSWlnCnFoN0RKdmZiMXlmLzFOVVBhTGFy
        UGNDM0hBY2UyNXVmY3ZKQUJsK1hhU1kKLS0tIFZXYnRkcHExK0lKTHg5emZyUXdp
        VWp4R09XVU5BREVaTFRHR0l5Vi8wRHMKyUrk/fr7AoXTGYZhVnh6L89DNfNtVYGF
        5Fy9ICWj9wCXegDpb0czfFdNreuEyluxDsm16acLnKDwIJ9KoXgZbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T14:28:33Z"
  mac: ENC[AES256_GCM,data:PMOl/ddBad8Lea2Cgs3JzWR4/WltF1JGUtg6PHswDr61NzNHU1mjjGbWVGLD1qM0dduzxlZ8DB0sy2y0CN2DDWeJNAuyjfWezQvndNTt78c6ReuAh5VAY87ZGMeRvDLRxWsBlsH2O2ywknq6lYch4NJYtYw2J8zNvrbkjPgV6nk=,iv:B5U92UyIvKLjKdtj0RtKtkbLxCPJ11JR66WMMfavObc=,tag:ZPK5COgqG3z1wiEupXvMVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
