# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: kopia
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:bprvtXAsS7kgHl6/INEJMEQjBspb3g6bdHkgzUngy8+phIJ+PVfJTDyqPWEw4Bu4,iv:J7vWxuHjdUZz0w1ZZzTkuIQpTd50F23PqdCZ2IGlU9M=,tag:+SHeLj8CwA8dEDJmGPK4CQ==,type:str]
sops:
  age:
    - recipient: age1mtlgldccglug7dl9n3dsme073t8hy6ppspdg36pm7mycqa5rgejsg0a56a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQ2FUZXBxYWFod0lTREc0
        M2JEczRWSzJEbnBtYWxOQUg0RU12bndweWx3Cml6UHc4VEliM2xZeC9tYWM3SzNp
        WFdrU09FVWxob2REdXpieW8zclRuWE0KLS0tIDlvbUxzMkx2OGRVSkFldVhZU2dx
        aFZKT0dSbGN1dS9XOFFHZHU1aWZFUVUKM12qAw/e708u6OEi9eRB41XIA9igFQ+A
        ctXSst/l/B0f8O9OvRJvdbLljkMufbuIGS+Dsm50UcrdUuiXyzvDXg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-18T23:31:37Z"
  mac: ENC[AES256_GCM,data:3s9L8y2InhwbfV1Gf3/cKk0L03tLU9pIknh1aKSyzzcKKxenUevDpzFTB5oHfkYa4jRIbTD7RZlIJC7FRerAOl/GiMjliAigongBxhZl7xXn6CLLWDNRYZSHX/q/spTeiOdcxeAne5or0ywW7bLWXnb4G4C6KmXR1ImD70uXLlY=,iv:XZNx2FqsS1aMInC8++t2OIyzOAmPsnBQqXpW7Q8ujtM=,tag:ohCVOqMl+rAkC0dPPGah+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
