---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-red
spec:
  components:
    - ../../../../components/volsync
  interval: 1h
  path: ./kubernetes/apps/home/node-red/app
  postBuild:
    substitute:
      APP: node-red
      VOLSYNC_CAPACITY: 1Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  patches:
    - target:
        kind: ReplicationSource
        name: node-red
      patch: |-
        - op: replace
          path: /spec/trigger/schedule
          value: "30 */2 * * *"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home
  wait: false
