---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
spec:
  components:
    - ../../../../components/volsync
  interval: 1h
  path: ./kubernetes/apps/home/home-assistant/app
  postBuild:
    substitute:
      APP: home-assistant
      VOLSYNC_CAPACITY: 10Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  patches:
    - target:
        group: volsync.backube
        version: v1alpha1
        kind: ReplicationSource
        name: home-assistant
        namespace: home
      patch: |-
        - op: replace
          path: /spec/trigger/schedule
          value: "0 2-23/2 * * *"

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home
  wait: false
